[Feature/model] 기능 1.2.1 - 커스텀 모델 적용 후 콘솔에 로깅 완, 기능 1.2.2 - 서버에 1분마다 POST 요청 틀만 잡음 (#1)
* fix(model): FileNotFoundError fix try 2

* feat(model): FileNotFoundError fix try 3

* fix(model): FileNotFoundError fix try 4

* feat(model): 웹캠 스트림 적용

* feat(model): 기능 1.2 웹캠 frame별로 모델 적용하기

* fix(기능-1.2.1): FIX NameError: name 'time' is not defined

* feat(기능-1.2.1): 웹캠 frame별로 모델 적용하기 > 로그 좀 더 자세하게

* fix(기능-1.2.1): FIX Attribute Error 'str' object has no attr 'name'

* feat(기능-1.2.1): 로깅 더 자세히

* fix(기능-1.2.1): FIX AttributeError: 'dict' object has no attribute 'name'

* feat(기능-1.2.1): confidence 소수점 아래 셋째자리까지 반올림

* feat(기능-1.2.1): 현재 시간도 로깅하도록

* feat(기능-1.2.1): 현재 시간 로깅할 때 HH:MM 형태로

* Revert "feat(기능-1.2.1): 현재 시간 로깅할 때 HH:MM 형태로"
This reverts commit 64d3c53b027a8b71fff7c13d3e40466935f970d3.

* chore(init): 라즈베리파이 기본 세팅

* feat(기능-1.2.1) 현재 시간 로깅할 때 HH:MM:SS 로

* feat(기능-1.2.2): 분 바뀔 때마다 로그 찍기

* feat(기능-1.2.2): 분 바뀔 때마다 request 보낼 코드 틀 잡기

* feat(기능-1.2.2): 분 바뀔 때마다 POST 성공 로그 찍는 부분 = 에서 * 로 수정